name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @angular/cli  # Install Angular CLI
      - run: npm ci  # Install dependencies based on package-lock.json
      - run: ng build  # Build the project
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TECHNEWS_97BE4 }}
          channelId: live
          projectId: technews-97be4
